# Generated by Django 5.0.6 on 2024-06-21 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("marketplace", "0002_butchery_deliveryfee_location"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
        migrations.AlterField(
            model_name="user",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific permissions for this user.",
                related_name="marketplace_user_permissions_set",
                related_query_name="user",
                to="auth.permission",
            ),
        ),
    ]
