# Generated by Django 5.0.6 on 2024-07-07 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='type',
            field=models.CharField(choices=[('farmer', 'Fermier'), ('buyer', 'Acheteur'), ('butcher', 'Boucherie')], default='farmer', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
