# Generated by Django 5.0.6 on 2024-07-11 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0006_user_fcm_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
