# Generated by Django 5.0.6 on 2024-07-12 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0007_user_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('butcher', 'Boucher'), ('farmer', 'Fermier')], max_length=255)),
                ('min_price', models.IntegerField(default=0)),
                ('max_price', models.IntegerField(blank=True, null=True)),
                ('price_increase_percentage', models.FloatField(blank=True, null=True)),
                ('fixed_price', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='ad',
            name='initial_price_per_kg',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='livraison',
            field=models.CharField(default='Not defined', max_length=255),
        ),
    ]
