from django.urls import path
from . import views
from .views import (
    UserListView, UserUpdateView, UserRetrieveView, UserDeleteView, UserAdsListView,  UserOrdersListView, 
    AdListView, AdValidateView, AdDeleteView, ButcheryAdsListView,UserOrderListView, UserOrderDetailView, 
    OrderListView, OrderUpdateView, OrderDeleteView, UserNotificationsView, save_fcm_token,
    get_stats, get_configs, add_to_cart, get_user_cart, CurrentUserView, get_nearby_farmers_ads, get_nearby_buyers_ads
)

urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('api/send_otp/', views.send_otp, name='send_otp'),
    path('api/verify_otp/', views.verify_otp, name='verify_otp'),
    path('api/register/', views.register, name='register'),
    path('api/login/', views.login, name='login'),
    path('api/logout/', views.logout, name='logout'),
    path('api/user/', CurrentUserView.as_view(), name='current-user'),
    path('api/users/<int:pk>/', UserRetrieveView.as_view(), name='user-retrieve'),
    path('api/users/update/<int:pk>/', UserUpdateView.as_view(), name='user-update'),
    path('api/users/<int:user_id>/ads/', UserAdsListView.as_view(), name='user-ads-list'),
    path('api/users/<int:user_id>/orders/', UserOrdersListView.as_view(), name='user-orders-list'),
    path('api/user/orders/', UserOrderListView.as_view(), name='user-orders'),
    path('api/user/orders/<int:pk>/', UserOrderDetailView.as_view(), name='user-order-detail'),
    path('api/ads/', views.AdListCreateView.as_view(), name='ad_list_create'),
    path('api/ads/<int:pk>/', views.AdRetrieveUpdateDestroyView.as_view(), name='ad_detail'),
    path('api/delivery_fees/', views.DeliveryFeeListCreateView.as_view(), name='delivery_fee_list_create'),
    path('api/delivery_fees/<int:pk>/', views.DeliveryFeeRetrieveUpdateDestroyView.as_view(), name='delivery_fee_detail'),
    path('api/butcheries/', views.ButcheryListCreateView.as_view(), name='butchery_list_create'),
    path('api/butchery_ads/', ButcheryAdsListView.as_view(), name='butchery-ads-list'),
    path('api/butcheries/<int:pk>/', views.ButcheryRetrieveUpdateDestroyView.as_view(), name='butchery_detail'),
    path('api/orders/', views.OrderListCreateView.as_view(), name='order_list_create'),
    path('api/orders/<int:pk>/', views.OrderRetrieveUpdateDestroyView.as_view(), name='order_detail'),
    path('api/notifications/', views.NotificationListCreateView.as_view(), name='notification_list_create'),
    path('api/notifications/<int:pk>/', views.NotificationRetrieveUpdateDestroyView.as_view(), name='notification_detail'),
    path('api/reviews/', views.ReviewListCreateView.as_view(), name='review_list_create'),
    path('api/reviews/<int:pk>/', views.ReviewRetrieveUpdateDestroyView.as_view(), name='review_detail'),
    path('api/carts/', views.CartListCreateView.as_view(), name='cart_list_create'),
    path('api/carts/<int:pk>/', views.CartRetrieveUpdateDestroyView.as_view(), name='cart_detail'),
    path('api/calculate_delivery_fee/', views.calculate_delivery_fee, name='calculate_delivery_fee'),
    path('api/admin/users/', UserListView.as_view(), name='user-list'),
    path('api/admin/users/<int:pk>/', UserUpdateView.as_view(), name='user-update'),
    path('api/admin/users/<int:pk>/delete/', UserDeleteView.as_view(), name='user-delete'),
    path('api/admin/ads/', AdListView.as_view(), name='ad-list'),
    path('api/admin/ads/<int:pk>/validate/', AdValidateView.as_view(), name='ad-validate'),
    path('api/admin/ads/<int:pk>/delete/', AdDeleteView.as_view(), name='ad-delete'),
    path('api/admin/orders/', OrderListView.as_view(), name='order-list'),
    path('api/admin/orders/<int:pk>/', OrderUpdateView.as_view(), name='order-update'),
    path('api/admin/orders/<int:pk>/delete/', OrderDeleteView.as_view(), name='order-delete'),
    path('api/admin/stats/', get_stats, name='get-stats'),
    path('api/api/configs/', get_configs, name='get_configs'),
    path('api/get_user_id/', views.get_user_id, name='get_user_id'),
    path('api/add_to_cart/', add_to_cart, name='add_to_cart'),
    path('api/get_user_cart/', get_user_cart, name='get_user_cart'),
    path('api/user/notifications/', UserNotificationsView.as_view(), name='user-notifications'),
    path('api/empty_cart/', views.empty_cart, name='empty_cart'),
    # autres routes
    path('api/ads/nearby_farmers/', get_nearby_farmers_ads, name='nearby_farmers_ads'),
    path('api/ads/nearby_buyers/', get_nearby_buyers_ads, name='nearby_buyers_ads'),
    path('api/save_fcm_token/', save_fcm_token, name='save_fcm_token'),

]
